---
- name: Node.js
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: 'nodejs_selection'
      prompt: "\nPlease choose the number for NodeJS version [ 1/2/3/4] \n\n
      1: NodeJS 10.x\n
      2: NodeJS 12.x\n
      3: NodeJS 13.x\n
      4: NodeJS 14.x\n"
      private: no
      default: 2

    - name: 'mongodb_selection'
      prompt: "\nPlease choose the number for MongoDB version [ 1/2/3/4...] \n\n
      1: MongoDB3.0(support Ubuntu16 and Redhat7 family)\n
      2: MongoDB3.2(support Ubuntu16 and Redhat7 family)\n
      3: MongoDB3.4(support Ubuntu16 and Redhat7 family)\n
      4: MongoDB3.6(support Ubuntu16 and Redhat7 family)\n
      5: MongoDB4.0\n
      6: MongoDB4.2\n"
      private: no
      default: 4

    - name: 'mysql_selection'
      prompt: "\nPlease choose the number for MySQL version [ 0/1/2/3/4] \n\n
      0: Don't install MySQL\n
      1: MySQL5.5(only for CentOS7.x, AmazonLinux)\n
      2: MySQL5.6(only for CentOS7.x, AmazonLinux, Ubuntu16.04 )\n
      3: MySQL5.7\n
      4: MySQL8.0\n"
      private: no
      default: 3

  vars:
    mysql_select:
      '0': ''
      '1': '5.5'
      '2': '5.6'
      '3': '5.7'
      '4': '8.0'
    mysql_version: "{{mysql_select[mysql_selection]}}" 

    mongodb_select:
      '1': '3.0'
      '2': '3.2'
      '3': '3.4'
      '4': '3.6'
      '5': '4.0'
      '6': '4.2'
    mongodb_version: "{{mongodb_select[mongodb_selection]}}" 

    nodejs_select:
      '1': '10'
      '2': '12'
      '3': '13'
      '4': '14'
    nodejs_version: "{{nodejs_select[nodejs_selection]}}" 

  pre_tasks:

    - include_vars: vars/add_mysql.yml
      when: mysql_version != ''

    - include_vars: roles/role_cloud/vars/cloud_download_url.yml
      when: region == '1' or region == 1

    - debug:
        msg: Nodejs will be installed, include  Nodejs{{nodejs_version}}, Mongodb{{mongodb_version}}, MySQL{{mysql_version}}

  roles:
  - { role: role_common , tags: "role_common"} 
  - { role: role_nodejs , tags: "role_nodejs"} 
  - { role: role_nginx , tags: "role_nginx"} 
  - { role: role_mysql , tags: "role_mysql", when: mysql_version != ''}
  - { role: role_mongodb , tags: "role_mongodb"}
  - { role: role_9panel , tags: "9panel"}
  - { role: role_docker , tags: "role_docker"} 
  - { role: role_redis , tags: "role_redis"}
  - { role: role_init , tags: "role_init"} 
  - { role: role_preend , tags: "role_preend"} 
  - { role: role_end , tags: "role_end"} 
